from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Lexicon:
    strong_keywords: tuple[str, ...]
    weak_keywords: tuple[str, ...]
    noise_phrases: tuple[str, ...]
    processing_tokens_strong: tuple[str, ...]
    processing_tokens_weak: tuple[str, ...]
    derivative_type_map: dict[str, str]
    derivative_priority: tuple[str, ...]
    audio_extensions: tuple[str, ...]


DEFAULT_LEXICON = Lexicon(
    strong_keywords=(
        "remix",
        "rmz",
        "bootleg",
        "mashup",
        "mash up",
        "rework",
        "flip",
        "vip",
        "dub",
        "nightcore",
        "speed up",
        "sped up",
        "speedup",
        "加速",
        "slowed",
        "slowed reverb",
        "slowed+reverb",
        "减速",
        "edit",
        "re-edit",
        "reedit",
        "改编",
        "混音",
        "串烧",
        "dj版",
        "dj version",
    ),
    weak_keywords=(
        "extended",
        "extended mix",
        "intro",
        "outro",
        "club mix",
        "radio edit",
        "version",
        "mix",
        "instrumental",
        "acoustic",
        "live",
        "demo",
        "clean",
        "explicit",
        "现场",
        "伴奏",
        "纯音乐",
        "口水版",
    ),
    noise_phrases=(
        "official video",
        "official audio",
        "lyrics",
        "lyric video",
        "mv",
        "高清",
        "完整版",
        "抖音热歌",
        "热门",
        "纯享",
        "现场录像",
    ),
    processing_tokens_strong=(
        "ai",
        "sync",
        "aligned",
        "align",
        "quantized",
        "quantize",
        "warp",
        "warped",
        "wav",
        "mp3",
        "flac",
        "aiff",
        "m4a",
        "export",
        "render",
        "bounced",
        "bounce",
        "stem",
        "stems",
        "acapella",
        "vocal",
        "instrumental_track",
        "structural",
        "structure",
        "struct",
        "analysis",
        "analyzed",
        "feature",
        "features",
        "cut",
        "trimmed",
        "chop",
        "chopped",
        "slice",
        "sliced",
        "loop",
        "looped",
        "phase",
        "phasefix",
        "phase_fixed",
        "corrected",
        "fix",
        "fixed",
        "keylocked",
        "key_lock",
        "keylock",
        "bpm",
        "tempo",
    ),
    processing_tokens_weak=(
        "mix",
        "master",
        "final",
        "v2",
        "v3",
        "v4",
        "edit2",
        "edit3",
        "take2",
        "take3",
        "demo2",
        "version",
        "ver",
        "rev",
        "r1",
        "r2",
        "intro",
        "outro",
        "extended",
    ),
    derivative_type_map={
        "remix": "REMIX",
        "rmz": "REMIX",
        "rework": "REMIX",
        "flip": "REMIX",
        "vip": "REMIX",
        "dub": "REMIX",
        "bootleg": "BOOTLEG",
        "mashup": "MASHUP",
        "mash up": "MASHUP",
        "nightcore": "SPEED_UP",
        "speed up": "SPEED_UP",
        "sped up": "SPEED_UP",
        "speedup": "SPEED_UP",
        "加速": "SPEED_UP",
        "slowed": "SLOWED",
        "slowed reverb": "SLOWED",
        "slowed+reverb": "SLOWED",
        "减速": "SLOWED",
        "edit": "EDIT",
        "re-edit": "EDIT",
        "reedit": "EDIT",
        "radio edit": "EDIT",
        "dj版": "EDIT",
        "dj version": "EDIT",
        "extended": "EXTENDED",
        "extended mix": "EXTENDED",
        "club mix": "EXTENDED",
        "mix": "VERSION",
        "version": "VERSION",
        "intro": "INTRO",
        "outro": "OUTRO",
        "instrumental": "INSTRUMENTAL",
        "伴奏": "INSTRUMENTAL",
        "纯音乐": "INSTRUMENTAL",
        "acoustic": "ACOUSTIC",
        "live": "LIVE",
        "现场": "LIVE",
        "demo": "VERSION",
        "clean": "VERSION",
        "explicit": "VERSION",
        "口水版": "VERSION",
        "改编": "EDIT",
        "混音": "REMIX",
        "串烧": "MASHUP",
    },
    derivative_priority=(
        "REMIX",
        "EDIT",
        "SPEED_UP",
        "SLOWED",
        "MASHUP",
        "BOOTLEG",
        "EXTENDED",
        "INTRO",
        "OUTRO",
        "LIVE",
        "ACOUSTIC",
        "INSTRUMENTAL",
        "VERSION",
        "UNKNOWN",
    ),
    audio_extensions=(
        "mp3",
        "wav",
        "flac",
        "m4a",
        "aiff",
        "aif",
        "ogg",
        "opus",
        "mp4",
        "aac",
    ),
)
